version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: favorite-place-mongodb
    env_file:
      - ./.env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_USER_PWD}
    ports:
      - '27017-27019:27017-27019'
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: favorite-place-redis
    ports:
      - '6379:6379'
    networks:
      - backend

networks:
  backend:
